### ISSUE TITLE
Failed at the tutorial@0.1.0 start script.

### ISSUE THREAD

**Issue by OfficialRuby** [john-smilga/react-hooks-tutorial-2020#5]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tutorial@0.1.0~prestart: tutorial@0.1.0
6 info lifecycle tutorial@0.1.0~start: tutorial@0.1.0
7 verbose lifecycle tutorial@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle tutorial@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/webdev/react-advanced-2020/node_modules/.bin:/home/webdev/.JSlib/bin:/home/webdev/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
9 verbose lifecycle tutorial@0.1.0~start: CWD: /home/webdev/react-advanced-2020
10 silly lifecycle tutorial@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle tutorial@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle tutorial@0.1.0~start: Failed to exec start script
13 verbose stack Error: tutorial@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid tutorial@0.1.0
15 verbose cwd /home/webdev/react-advanced-2020/src
16 verbose Linux 4.19.0-11-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error tutorial@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the tutorial@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by OfficialRuby** [comment]
This was a problem from my node, I there was a problem in my node user privileged setup.
